HBackOrganization:
    type: entity
    table: h_back_organization
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: true
            length: 255
            fixed: false
        description:
            type: string
            nullable: true
            length: 255
            fixed: false
        name:
            type: string
            nullable: true
            length: 255
            fixed: false
        orgTypeId:
            type: integer
            nullable: true
            unsigned: false
            column: org_type_id
        status:
            type: integer
            nullable: true
            unsigned: false
        version:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }
