HModuleIndustory:
    type: entity
    table: h_module_industory
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: true
            length: 255
            fixed: false
        createTime:
            type: datetime
            nullable: true
            column: create_time
        description:
            type: string
            nullable: true
            length: 255
            fixed: false
        name:
            type: string
            nullable: true
            length: 255
            fixed: false
        version:
            type: string
            nullable: true
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
