HShopProduct:
    type: entity
    table: h_shop_product
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: true
            length: 255
            fixed: false
        createTime:
            type: datetime
            nullable: true
            column: create_time
        delistTime:
            type: datetime
            nullable: true
            column: delist_time
        industryId:
            type: integer
            nullable: true
            unsigned: false
            column: industry_id
        isaddtag:
            type: integer
            nullable: true
            unsigned: false
        isaddcategory:
            type: integer
            nullable: true
            unsigned: false
        status:
            type: integer
            nullable: true
            unsigned: false
        style:
            type: string
            nullable: true
            length: 255
            fixed: false
        type:
            type: integer
            nullable: true
            unsigned: false
        listTime:
            type: datetime
            nullable: true
            column: list_time
        modifyTime:
            type: datetime
            nullable: true
            column: modify_time
        picUrl:
            type: string
            nullable: true
            length: 600
            fixed: false
            column: pic_url
        shopId:
            type: integer
            nullable: true
            unsigned: false
            column: shop_id
        templateId:
            type: integer
            nullable: true
            unsigned: false
            column: template_id
        version:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }
