HShopIndustry:
    type: entity
    table: h_shop_industry
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: true
            length: 255
            fixed: false
        createTime:
            type: datetime
            nullable: true
            column: create_time
        level:
            type: integer
            nullable: true
            unsigned: false
        status:
            type: integer
            nullable: true
            unsigned: false
        modifyTime:
            type: datetime
            nullable: true
            column: modify_time
        name:
            type: string
            nullable: true
            length: 255
            fixed: false
        description:
            type: string
            nullable: true
            length: 255
            fixed: false
        parentId:
            type: integer
            nullable: true
            unsigned: false
            column: parent_id
        sortNo:
            type: integer
            nullable: true
            unsigned: false
            column: sort_no
        version:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }
