Products:
    type: entity
    table: products
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
    manyToMany:
        bug:
            targetEntity: Bugs
            cascade: {  }
            mappedBy: product
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
